-- return require('packer').startup(function(use)
-- 	use 'wbthomason/packer.nvim'
--
-- 	use {
-- 		'nvim-telescope/telescope.nvim', tag = '0.1.6',
-- 		requires = { {'nvim-lua/plenary.nvim'}, {'BurntSushi/ripgrep'}, {'sharkdp/fd'} }
-- 	}
--
-- 	use {
-- 		'VonHeikemen/lsp-zero.nvim',
-- 		branch = 'v3.x',
-- 		requires = {
-- 			{'williamboman/mason.nvim'},
-- 			{'williamboman/mason-lspconfig.nvim'},
--
-- 			{'neovim/nvim-lspconfig'},
-- 			{'hrsh7th/nvim-cmp'},
-- 			{'hrsh7th/cmp-nvim-lsp'},
-- 			{'L3MON4D3/LuaSnip'},
-- 		}
-- 	}
--
--     use {
--         'nvim-treesitter/nvim-treesitter',
--         run = function()
--             local ts_update = require('nvim-treesitter.install').update({ with_sync = true })
--             ts_update()
--         end,
--     }
-- 	use('tpope/vim-fugitive')
-- 	use('tpope/vim-surround')
--     use('tpope/vim-commentary')
--     use {
--         'akinsho/flutter-tools.nvim',
--         requires = {
--             'nvim-lua/plenary.nvim',
--             'stevearc/dressing.nvim', -- optional for vim.ui.select
--         },
--     }
-- end)
