-- local lsp_zero = require('lsp-zero')
--
-- lsp_zero.on_attach(function(client, bufnr)
-- 	-- see :help lsp-zero-keybindings
-- 	-- to learn the available actions
-- 	lsp_zero.default_keymaps({buffer = bufnr})
-- end)
--
-- require('mason').setup({})
-- require('mason-lspconfig').setup({
-- 	-- Replace the language servers listed here
-- 	-- with the ones you want to install
-- 	ensure_installed = {'tsserver', 'rust_analyzer', 'lua_ls', 'pyright'},
-- 	handlers = {
-- 		function(server_name)
-- 			require('lspconfig')[server_name].setup({})
-- 		end,
-- 	},
-- })
--
-- local cmp = require('cmp')
--
-- cmp.setup({
-- 	mapping = cmp.mapping.preset.insert({
-- 		['<Tab>'] = cmp.mapping.confirm({ select = true }),
-- 		['<C-c>'] = cmp.mapping.complete(),
-- 		['<C-k>'] = cmp.mapping.select_prev_item(),
-- 		['<C-j>'] = cmp.mapping.select_next_item(),
-- 	}),
-- 	snippet = {
-- 		expand = function(args)
-- 			require('luasnip').lsp_expand(args.body)
-- 		end,
-- 	},
-- })
--
