-- local builtin = require('telescope.builtin')
-- vim.keymap.set('n', '<leader>ff',builtin.find_files, { desc = "[F]ind [F]iles" })
-- vim.keymap.set('n', '<leader>pf', builtin.git_files, { desc = "[P]roject [F]iles" })
--
-- -- Save the current buffer before switching with telescope
-- vim.api.nvim_create_autocmd("BufLeave", {
--   pattern = "*",
--   command = "silent! update"
-- })
--
